In [7]:
import numpy as np  
  
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
  
print("Please write the elements of the matrix in a single line and separated by a space: ")  
elements = list(map(int, input().split()))  
matrixx = np.array(elements).reshape(Rows, Columns)  
print(matrixx)  
R = int(input("Give the number of rows:"))  
C = int(input("Give the number of columns:"))  
print("Please write the elements of the matrix in a single line and separated by a space: ")  
e= list(map(int, input().split()))   
m = np.array(e).reshape(R, C)  
print(m) 

Give the number of rows:3
Give the number of columns:3
Please write the elements of the matrix in a single line and separated by a space: 
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Give the number of rows:3
Give the number of columns:3
Please write the elements of the matrix in a single line and separated by a space: 
1 3 5 7 9 2 4 6 8
[[1 3 5]
 [7 9 2]
 [4 6 8]]


In [9]:
d=np.dot(matrixx,m)
print(d)

[[ 27  39  33]
 [ 63  93  78]
 [ 99 147 123]]


In [11]:
print(matrixx.transpose())
print()
print(m.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 7 4]
 [3 9 6]
 [5 2 8]]


In [13]:
print(matrixx.trace())
print(m.trace())

15
18


In [15]:
print(np.linalg.matrix_rank(matrixx))
print(np.linalg.matrix_rank(m))

2
3


In [23]:
print(np.linalg.det(matrixx))
print(np.linalg.det(m))

-9.51619735392994e-16
-54.00000000000001


In [30]:
print(np. linalg. inv(matrixx))
print(np. linalg. inv(m))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


In [31]:
print(np.linalg.eig(matrixx))
print(np.linalg.eig(m))

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
(array([15.4422907 , -0.98661655,  3.54432584]), array([[ 0.36886455,  0.81664483,  0.37173179],
       [ 0.61669356, -0.57673733, -0.7003462 ],
       [ 0.69543367,  0.02157037,  0.60936908]]))
