In [7]:
import numpy as np
x=np.arange(1,10).reshape(3,3)
y=np.arange(11,20).reshape(3,3)
print(x)
print()
print(y)
print()
print(np.multiply(x,y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
