In [9]:
import numpy as np
n=np.arange(1,17).reshape(4,4)
print(n)
print()
n[[0,-1],:]=n[[-1,0],:]
print(n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
