In [11]:
import numpy as np
x=np.arange(10,19).reshape(3,3)
print(x)
a=np.sum(x)
print("Total sum",a)
b=np.sum(x,axis=1)
print("row sum",b)
c=np.sum(x,axis=0)
print("col sum",c)


[[10 11 12]
 [13 14 15]
 [16 17 18]]
Total sum 126
row sum [33 42 51]
col sum [39 42 45]
